# Use this file to construct an environment
# for developing napari-imagej from source.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create -f dev-environment.yml
#   conda activate napari-imagej-dev
#
# In addition to the dependencies needed for using napari-imagej, it includes
# tools for developer-related actions like running automated tests (pytest),
# linting the code (black), and generating the API documentation (sphinx).
# If you want an environment without these tools, use environment.yml.
name: napari-imagej-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.8
  # Project dependencies
  - confuse
  - jpype1 >= 1.4.1
  - labeling >= 0.1.12
  - magicgui >= 0.5.1
  - napari
  - numpy
  - openjdk=8
  - pyimagej >= 1.3.0
  - scyjava >= 1.8.1
  # Developer tools
  - autopep8
  - black
  - build
  - flake8
  - isort
  - pre-commit
  - pyqt5-sip
  - pytest
  - pytest-cov
  - pytest-env
  - pytest-qt
  - qtpy
  # Project from source
  - pip
  - pip:
    - validate-pyproject[all]
    - -e '.'
