[build-system]
# Setuptools version constraint ensures PEP 517 compatibility
requires = [
    "setuptools >= 45",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
env = [
    "NAPARI_IMAGEJ_TESTING=yes"
]