# napari-imagej Default Settings

# USERS BEWARE:
# This yaml file will soon be replaced with napari's contribution configuration.

# Path to a local ImageJ2 installation (e.g. /Applications/Fiji.app),
# OR version of net.imagej:imagej artifact to launch (e.g. 2.3.0),
# OR endpoint of another artifact built on ImageJ2 (e.g. sc.fiji:fiji),
# OR list of Maven artifacts to include (e.g.
#   ['net.imagej:imagej:2.3.0', 'net.imagej:imagej-legacy', 'net.preibisch:BigStitcher']).
# The default ('net.imagej:image') will use the latest version of ImageJ2,
# downloading it if needed.
imagej_directory_or_endpoint: 'net.imagej:imagej'

# Path to the ImageJ base directory on your local machine.
# Defaults to the current working directory
imagej_base_directory: '.'

# This can be used to include original ImageJ functionality.
# Iff True, original ImageJ functionality (ij.* packages) will be available.
include_imagej_legacy: false

# Designates the mode of execution for ImageJ2.
# Allowed options are 'headless' and 'interactive'.
# NB 'interactive' mode is unavailable on MacOS. More details can be found at
# https://pyimagej.readthedocs.io/en/latest/Initialization.html#interactive-mode
# If napari-imagej is launched on MacOS with this setting set to "interactive",
# the setting will silently be reassigned to "headless"
jvm_mode: 'interactive'

# This can be used to identify whether transferred data between ImageJ2 and napari
# should be selected via activation or by user selection via a dialog.
# By default, the active layer/window is chosen for transfer between applications.
# By setting this value to false, a popup will be shown instead.
choose_active_layer: true